apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-application-sets
spec:
  project: default
  source:
    path: argo-cd-apps/environments/staging
    repoURL: https://github.com/amisstea/eks-infra-deployments.git
    targetRevision: update_readme
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
